spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles:
    active: dev
  application: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles:
    active: test
  application: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/